spring.application.name=mensal
spring.datasource.url=jdbc:mysql://database.dua.dev.br:3306/mensal
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:5001/realms/bia-mensal

keycloak.admin.realm=master
keycloak.admin.client-id=debora
keycloak.admin.secret=yZmrlIJYBht8weP0Pqq3JgyDwoGfwEy7
app.role.prefix=sys-alpha